fn main() {
    // The headless adapter reuses production SSH/CLI/MCP modules but never
    // instantiates AppWindow, avoiding its generated UI code on small servers.
    if std::env::var_os("CARGO_FEATURE_HEADLESS").is_some() {
        return;
    }
    generate_bundled_font_coverage();
    // Some MinGW-w64 distributions (winlibs' "MCF" builds, which thread through
    // mcfgthread) need the mcfgthread import library on the link line, otherwise
    // libgcc_eh.a's emutls.o is left with undefined `_MCF_*` symbols and the
    // link fails. The flag is only added when the library actually exists, so
    // MSVC and winpthreads-based toolchains stay untouched.
    #[cfg(all(windows, target_env = "gnu"))]
    {
        let target = std::env::var("TARGET").unwrap_or_default();
        let arch = target.split('-').next().unwrap_or("x86_64").to_string();
        // The MinGW driver is named after the *host* (x86_64-w64-mingw32-gcc …),
        // not after Rust's own triple (x86_64-pc-windows-gnu), so try both.
        let compilers = [
            format!("{arch}-w64-mingw32-gcc"),
            format!("{target}-gcc"),
            "gcc".to_string(),
        ];
        for compiler in compilers {
            let Ok(out) = std::process::Command::new(&compiler)
                .arg("-print-file-name=libmcfgthread.a")
                .output()
            else {
                continue;
            };
            let path = String::from_utf8_lossy(&out.stdout).trim().to_string();
            // `-print-file-name` echoes the name unchanged when nothing matched.
            if std::path::Path::new(&path).is_file() {
                println!("cargo:rustc-link-arg=-lmcfgthread");
                break;
            }
        }
    }
    // Bundle the gettext `.po` translations under `lang/` so the UI's `@tr(...)`
    // strings can switch language at runtime via slint::select_bundled_translation.
    // Source language is Chinese (the msgids); `lang/<lc>/LC_MESSAGES/meatshell.po`
    // provides other locales.  No per-component context, so msgids are the raw
    // Chinese strings.
    println!("cargo:rerun-if-changed=lang");
    slint_build::compile_with_config(
        "ui/app.slint",
        slint_build::CompilerConfiguration::new()
            .with_style("fluent".into())
            .with_bundled_translations("lang")
            .with_default_translation_context(slint_build::DefaultTranslationContext::None),
    )
    .expect("Slint build failed");

    // Embed the application icon into the Windows executable so it shows up in
    // Explorer, the taskbar and shortcuts. No-op on non-Windows targets.
    #[cfg(windows)]
    {
        println!("cargo:rerun-if-changed=assets/meatshell.ico");
        println!("cargo:rerun-if-changed=assets/meatshell.exe.manifest");
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/meatshell.ico");
        // Embed an application manifest declaring Per-Monitor DPI Awareness V2.
        // Without it the DPI-awareness level depends on winit's runtime
        // SetProcessDpiAwarenessContext call, which races: if anything touches a
        // DPI API first the call silently fails and the window jumps in size /
        // cursor offset when dragged across monitors with different scaling (#194).
        // The manifest is authoritative and applied before any code runs.
        res.set_manifest_file("assets/meatshell.exe.manifest");
        if let Err(e) = res.compile() {
            println!("cargo:warning=failed to embed Windows icon: {e}");
        }
    }
}

/// Emit the bundled terminal font's Unicode coverage as a compact table of
/// inclusive codepoint ranges (#461). At runtime the terminal uses it to spot
/// glyphs Meatshell Mono lacks (e.g. `➜` in a custom PS1) and draw just those
/// with a system fallback font, without embedding a second copy of the font
/// or re-parsing it on startup.
fn generate_bundled_font_coverage() {
    const FONT: &str = "ui/fonts/MeatshellMono-Regular.ttf";
    println!("cargo:rerun-if-changed={FONT}");
    let data = std::fs::read(FONT).expect("read bundled terminal font");
    let face = ttf_parser::Face::parse(&data, 0).expect("parse bundled terminal font");
    let mut codepoints = Vec::new();
    if let Some(cmap) = face.tables().cmap {
        for subtable in cmap.subtables {
            if !subtable.is_unicode() {
                continue;
            }
            subtable.codepoints(|cp| {
                if subtable.glyph_index(cp).is_some_and(|glyph| glyph.0 != 0) {
                    codepoints.push(cp);
                }
            });
        }
    }
    codepoints.sort_unstable();
    codepoints.dedup();
    let mut ranges: Vec<(u32, u32)> = Vec::new();
    for cp in codepoints {
        match ranges.last_mut() {
            Some((_, end)) if *end + 1 == cp => *end = cp,
            _ => ranges.push((cp, cp)),
        }
    }
    let mut out = String::from(
        "// @generated by build.rs from ui/fonts/MeatshellMono-Regular.ttf\n\
         pub(crate) const BUNDLED_FONT_COVERAGE: &[(u32, u32)] = &[\n",
    );
    for (start, end) in ranges {
        out.push_str(&format!("    (0x{start:X}, 0x{end:X}),\n"));
    }
    out.push_str("];\n");
    let path =
        std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("bundled_font_coverage.rs");
    std::fs::write(path, out).expect("write bundled font coverage table");
}
